"""
Builds a URL for the dynamic vehicle reference card image.

The image is generated by the Next.js route handler at /api/vehicle-card
which renders a colored card with vehicle type emoji, color, and make.
"""
import urllib.parse

BASE_URL = "https://amberangels.org/api/vehicle-card"


def resolve_vehicle_image_url(
    *,
    color: str | None = None,
    body_type: str | None = None,
    make: str | None = None,
) -> str | None:
    """Return a URL for the vehicle reference card, or None if no useful data."""
    if not color and not body_type and not make:
        return None

    params: dict[str, str] = {}
    if color:
        params["color"] = color.lower()
    if body_type:
        params["type"] = body_type.lower()
    if make:
        params["make"] = make
    return f"{BASE_URL}?{urllib.parse.urlencode(params)}"
